use serde::{Deserialize, Serialize};

// ── Legacy plan (kept for serde compatibility with existing sync state) ───────
//
// The app no longer uses a static 7-day plan. ScheduledWorkout replaces
// WorkoutDay as the unit of work. These types remain only so old state.json
// files deserialize without errors; new state never writes them.

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct WorkoutPlan {
    pub days: Vec<WorkoutDay>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct WorkoutDay {
    pub id: String,
    pub name: String,
    pub exercises: Vec<Exercise>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Exercise {
    pub id: String,
    pub name: String,
    pub target_sets: u32,
    pub reps_min: u32,
    pub reps_max: u32,
    #[serde(default)]
    pub category: ExerciseCategory,
    pub notes: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub enum ExerciseCategory {
    #[default]
    Main,
    Core,
    Cardio,
}

// ── User goals ────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct UserGoals {
    pub primary_goal: PrimaryGoal,
    pub sessions_per_week: u32,
    pub session_minutes: u32,
    /// Equipment identifiers (matches free-exercise-db `equipment` strings:
    /// "barbell", "dumbbell", "machine", "cable", "kettlebells", "body only",
    /// "bands", "exercise ball", etc.) Empty = assume full gym.
    pub equipment: Vec<String>,
    /// Free text: injuries, lifts to avoid, asymmetries, prior surgeries.
    pub avoid: String,
    /// Free text: anything else the coach should know.
    pub notes: String,
    /// Target aerobic minutes per week (sum of cardio session durations).
    /// None = no target set; coach falls back to generic prescription based on primary_goal.
    #[serde(default)]
    pub weekly_cardio_minutes_target: Option<u32>,
    /// Most recent VO2 max reading, manually entered or imported from an Apple Health screenshot.
    #[serde(default)]
    pub vo2_max_latest: Option<f32>,
    /// YYYY-MM-DD the VO2 max reading is from. Used to drop stale imports.
    #[serde(default)]
    pub vo2_max_updated: Option<String>,
    #[serde(default)]
    pub mobility_focus: FocusLevel,
    #[serde(default)]
    pub balance_focus: FocusLevel,
}

impl Default for UserGoals {
    fn default() -> Self {
        Self {
            primary_goal: PrimaryGoal::default(),
            sessions_per_week: 4,
            session_minutes: 60,
            equipment: vec![],
            avoid: String::new(),
            notes: String::new(),
            weekly_cardio_minutes_target: None,
            vo2_max_latest: None,
            vo2_max_updated: None,
            mobility_focus: FocusLevel::default(),
            balance_focus: FocusLevel::default(),
        }
    }
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Default)]
pub enum FocusLevel {
    Low,
    #[default]
    Standard,
    High,
}

impl FocusLevel {
    pub fn label(&self) -> &'static str {
        match self {
            Self::Low => "Low",
            Self::Standard => "Standard",
            Self::High => "High",
        }
    }
    pub fn all() -> &'static [FocusLevel] {
        &[Self::Low, Self::Standard, Self::High]
    }
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Default)]
pub enum PrimaryGoal {
    #[default]
    Hypertrophy,
    Strength,
    FatLoss,
    Endurance,
    GeneralFitness,
}

impl PrimaryGoal {
    pub fn label(&self) -> &'static str {
        match self {
            Self::Hypertrophy => "Hypertrophy",
            Self::Strength => "Strength",
            Self::FatLoss => "Fat loss",
            Self::Endurance => "Endurance",
            Self::GeneralFitness => "General fitness",
        }
    }
    pub fn all() -> &'static [PrimaryGoal] {
        &[
            Self::Hypertrophy,
            Self::Strength,
            Self::FatLoss,
            Self::Endurance,
            Self::GeneralFitness,
        ]
    }
}

/// Canonical equipment list shown in the goals editor (matches free-exercise-db).
pub const EQUIPMENT_OPTIONS: &[&str] = &[
    "barbell",
    "dumbbell",
    "machine",
    "cable",
    "kettlebells",
    "body only",
    "bands",
    "exercise ball",
    "e-z curl bar",
    "other",
];

// ── Scheduled workouts (the new core unit) ────────────────────────────────────

/// A single planned workout for a specific date. Generated by the AI coach,
/// or created manually as a fallback.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ScheduledWorkout {
    pub id: String,
    /// YYYY-MM-DD — the date this workout is intended for.
    pub date: String,
    pub name: String,
    /// Coach's reasoning: which muscles, why this volume, recovery notes.
    #[serde(default)]
    pub rationale: String,
    #[serde(default)]
    pub source: WorkoutSource,
    pub exercises: Vec<ScheduledExercise>,
    /// ISO 8601 timestamp when the workout was generated/created.
    #[serde(default)]
    pub created_at: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub enum WorkoutSource {
    #[default]
    Coach,
    Manual,
}

/// Apple-Health-style HR zone budget. Used both as a coach prescription
/// (`target_zones`) and as a per-set actual (`zone_minutes`). Zone 1-5 maps
/// to the standard Apple Watch HR zones; we don't try to redefine them.
///
/// `minutes` is `f32`, not `u32`, because Apple Health samples HR continuously
/// and reports fractional zone time (e.g. `17.85` min in Z2). Legacy JSON
/// with integer values like `"minutes": 30` still deserializes — serde reads
/// integers into floats without complaint.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ZoneTarget {
    pub zone: u8,
    pub minutes: f32,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ScheduledExercise {
    /// `LibraryExercise.id` from /data/exercises.json. None = freeform name only.
    pub library_id: Option<String>,
    pub name: String,
    pub target_sets: u32,
    pub reps_min: u32,
    pub reps_max: u32,
    #[serde(default)]
    pub rest_seconds: u32,
    pub notes: Option<String>,
    #[serde(default)]
    pub target_duration_seconds: Option<u32>,
    /// Coach-prescribed HR zone breakdown for cardio. When `Some`, the
    /// session UI shows one input per zone instead of min × RPE.
    #[serde(default)]
    pub target_zones: Option<Vec<ZoneTarget>>,
}

// ── Session (in-progress / completed workout) ────────────────────────────────

/// Active workout being logged. `day_id`/`day_name` correspond to the
/// ScheduledWorkout id/name (kept for stored-history compatibility).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct WorkoutSession {
    pub id: String,
    pub date: String,
    pub day_id: String,
    pub day_name: String,
    pub exercise_logs: Vec<ExerciseLog>,
    pub is_complete: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ExerciseLog {
    pub exercise_id: String,
    pub exercise_name: String,
    pub target_sets: u32,
    pub reps_min: u32,
    pub reps_max: u32,
    pub sets: Vec<SetLog>,
    #[serde(default)]
    pub target_duration_seconds: Option<u32>,
    /// Mirrors the prescription's `target_zones` so the session UI can
    /// render zone inputs without re-reading the original ScheduledExercise.
    #[serde(default)]
    pub target_zones: Option<Vec<ZoneTarget>>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct SetLog {
    pub set_number: u32,
    pub reps: u32,
    #[serde(alias = "weight_lbs")]
    pub weight: f32,
    pub completed: bool,
    #[serde(default)]
    pub completed_date: Option<String>,
    #[serde(default)]
    pub duration_seconds: Option<u32>,
    /// Actual minutes-per-zone the user logged for this set. Only ever
    /// populated for zone-shaped cardio sets; None for everything else.
    #[serde(default)]
    pub zone_minutes: Option<Vec<ZoneTarget>>,
}

// ── Flat exercise-entry history (unchanged) ───────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ExerciseEntry {
    pub id: String,
    pub date: String,
    pub exercise_name: String,
    pub exercise_id: String,
    pub session_id: Option<String>,
    pub day_id: Option<String>,
    pub day_name: Option<String>,
    pub target_sets: u32,
    pub reps_min: u32,
    pub reps_max: u32,
    pub sets: Vec<SetLog>,
    #[serde(default)]
    pub finalized: bool,
    #[serde(default)]
    pub created_at: String,
    #[serde(default)]
    pub target_duration_seconds: Option<u32>,
}

// ── Library exercise (deserialized from /data/exercises.json) ────────────────

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LibraryExercise {
    pub id: String,
    pub name: String,
    pub force: Option<String>,
    pub level: String,
    pub mechanic: Option<String>,
    pub equipment: Option<String>,
    #[serde(rename = "primaryMuscles", default)]
    pub primary_muscles: Vec<String>,
    #[serde(rename = "secondaryMuscles", default)]
    pub secondary_muscles: Vec<String>,
    #[serde(default)]
    pub instructions: Vec<String>,
    pub category: String,
    #[serde(default)]
    pub images: Vec<String>,
}

// ── Muscle group taxonomy ────────────────────────────────────────────────────
//
// free-exercise-db uses 17 muscle keys; the body heatmap renders 15 visual
// regions (chest, shoulders, biceps, triceps, forearms, abs, obliques, lats,
// mid-back, lower back, traps, glutes, quads, hamstrings, calves, plus
// neck/abductors/adductors as small extras). The same `Muscle` key drives both
// heatmap coloring and library filtering.

pub const ALL_MUSCLES: &[&str] = &[
    "chest",
    "shoulders",
    "biceps",
    "triceps",
    "forearms",
    "abdominals",
    "lats",
    "middle back",
    "lower back",
    "traps",
    "glutes",
    "quadriceps",
    "hamstrings",
    "calves",
    "abductors",
    "adductors",
    "neck",
];

/// Human-readable label for a free-exercise-db muscle key.
pub fn muscle_label(key: &str) -> &str {
    match key {
        "abdominals" => "Abs",
        "middle back" => "Mid back",
        "lower back" => "Lower back",
        "quadriceps" => "Quads",
        _ => key,
    }
}
